name: Publish
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITEA_USERNAME: ${{ secrets.GITEA_USERNAME }}
      GITEA_PASSWORD: ${{ secrets.GITEA_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 13
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build

      - name: Upload main Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LavaSrc.jar
          path: plugin/build/libs/plugin-*.jar

      - name: Upload plugin Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LavaSrc-Plugin.jar
          path: plugin/build/libs/plugin-*.jar

      - name: Publish
        run: ./gradlew publish

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: |
            LavaSrc.jar
            LavaSrc-Plugin.jar

      - name: Upload Artifacts to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            LavaSrc.jar
            LavaSrc-Plugin.jar
          allowUpdates: true